project:
  type: website
  output-dir: docs

lang: de

website:
  title: "Modellierung von Längs­schnitt­daten"
  navbar: 
    pinned: true
  sidebar:
    logo: img/logo.svg
    contents:
      - index.qmd
      - Methodologie des Längssschnitts.qmd
      - Einfache lineare Regression.qmd
      - Multiple lineare Regression.qmd
      - Längsschnittliche Modelle im Überblick.qmd
      # - Longitudinale Single-Level Regressionen.qmd

format:
  live-html:
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 3 
    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300     
    css: 
      - brand.css     
      - exams/webex.css
    include-after-body: exams/webex.js

author:
  - name: Samuel Merk
    corresponding: true
    orcid: 0000-0003-2594-5337
    email: merk@ph-karlsruhe.de
    affiliations:
      - id: id1
        name: "Pädagogische Hochschule Karlsruhe"
        address: Bismarckstraße 10
        city: Karlsruhe
        country: Germany
        postal-code: 76133

csl: apa.csl
bibliography: references.bib